language: node_js
node_js:
- '9'
before_install:
  - npm i -g makeshift && makeshift -s @adidas -r registry.npmjs.org
deploy:
  provider: npm
  email: uxteam@adidas-group.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: adidas/htmplar
    branch: master
  skip_cleanup: true
notifications:
  email:
    recipients:
    - berkan.dirim@adidas.com
    on_success: change
    on_failure: always
